apiVersion: v1
kind: Service
metadata:
  name: praksa-task-api-service
  namespace: praksa-task
spec:
  selector:
    app: praksa-task-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP