name: Build and Push Docker Image
 
on:
  push:
    branches: 
        - main
 
jobs:
  build:
    runs-on: runner-api
 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
 
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
 
      - name: Build and Push 
        shell: powershell
        run: |
          if ("${{ github.ref_name }}" -eq "main") {
            echo "##vso[task.setvariable variable=ENVIRONMENT]main"
          } else {
            echo "##vso[task.setvariable variable=ENVIRONMENT]dev"
          }          
          Set-Location -Path "./src"
          $imageName = "ghcr.io/gusmarko/praksa-task-api/praksa-task-api:${{ env.ENVIRONMENT }}latest"
          docker build --build-arg ENVIRONMENT=${{ env.ENVIRONMENT }} -t $imageName .
          docker push $imageName
